# Lab-0: 

In this lab we set up a deep learning workstation on your local machine. Then we work through some fundamental math and python review content. 

**Instructions** 
* Read and work through all tutorial content and do all exercises below
  
**Submission:**
* Upload a PDF (or HTML) of the completed form of this notebook to Canvas when you are done 
* The final uploaded version should NOT have any code-errors present 
* All outputs must be visible in the uploaded version, including code-cell outputs, images, graphs, etc
* **DO NOT upload .ipynb, this will not be graded and will result in a zero**

# Part-1: Install Pytorch and Tensorflow

* Use the following commands to install Tensorflow, Keras, and Pytorch into a dedicated Conda environment named (ANLY590). 
* These command can be run from the command line (on mac/linux) or Anaconda Power-shell (windows). 
* Only paste the lines without "#"  (i.e. exclude comments).


The following commands seem to work on both intel and M1 macs. However, if it is already working then don't change anything.

```
conda deactivate
conda env remove -n ANLY590
conda activate ANLY590
conda create -n ANLY590 python=3.10
conda activate ANLY590
conda install pytorch torchvision torchaudio -c pytorch
conda install -c conda-forge tensorflow
conda install scipy
conda install -c conda-forge matplotlib
conda install -c anaconda pandas
conda install ipykernel --update-deps --force-reinstall
```
If those don't work consider using the following

```
#------------------
#SET UP A DEDICATED CONDA ENVIROMENT 
#------------------
conda deactivate 
conda create -n ANLY590 python=3.10
conda activate ANLY590

#------------------
#INSTALL PYTORCH: https://pytorch.org/
#------------------
#MACOS USE:
conda install pytorch torchvision torchaudio -c pytorch

#LINUX USE:
conda install pytorch torchvision torchaudio cpuonly -c pytorch

#WINDOWS USE:
conda install pytorch torchvision torchaudio cpuonly -c pytorch

#------------------
#INSTALL TENSORFLOW: 
#------------------

#INTEL MAC AND WINDOWS USERS 
python -m pip install --upgrade pip
python -m pip install tensorflow


#MAC M1 USERS 
conda install -c apple tensorflow-deps -y
python -m pip install --upgrade pip
python -m pip install tensorflow-macos
python -m pip install tensorflow-metal
#for more details see the following video
#https://www.youtube.com/watch?v=4nY5lDBXdOg&t=88s (Links to an external site.)


#------------------
# ADDITIONAL PACKAGES
#------------------
conda install scipy
conda install -c conda-forge matplotlib
conda install -c anaconda pandas
conda install ipykernel --update-deps --force-reinstall

```

* MAC M1 USERS; YOU NEED XCODE, HOME-BREW, CONDA INSTALLED 
* 1) HOMEBREW: install homebrew if you don't have it (run following from command line)
  * /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh (Links to an external site.))"
* At the end of the installation it will provide you with two commands to add brew to your path, look for the commands after the following line and paste them into your browser   "Run these two commands in your terminal to add Homebrew to your PATH:"
* XCODE: If xcodes is not installed then install it from app-store. If it is installed then check app-store to make sure Xcodes is up to date (run update if needed) 
* CONDA: If you don't have conda or mini-conda installed then follow the standard MacOS installation method found on the conda website. 
* Once Homebrew, Xcodes, conda are installed run the following 

* This installation process worked on my intel Mac. 
* That being said, the installation process can be buggy and sometimes the packages do not "play-nice" with each other


# Part-2: Make sure installation was successful

**Important**: Restart VS code and switch to the ANLY590 interpreter in the upper right corner of VS code 

In [2]:
import torch
x = torch.rand(5, 3)
print(x, type(x))

tensor([[0.4894, 0.2626, 0.2289],
        [0.8978, 0.0879, 0.7886],
        [0.0682, 0.3298, 0.8895],
        [0.2505, 0.6381, 0.9406],
        [0.2996, 0.7911, 0.5104]]) <class 'torch.Tensor'>


In [5]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import initializers

model = keras.Sequential([layers.Dense(1,activation='sigmoid',input_shape=(1,)),])

print(model.summary()); 

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
None


# Part-2: Python Objects and Classes

* **THIS SECTION IS VERY IMPORTANT: READ CAREFULLY**
  <br />
* Understanding the concept of "classes and objects" is completely fundamental to understanding python. 
  * This is because Python is an object oriented programming (OOP) language. 
  * Which means that EVERYTHING in python is an object (of some python class).
  * We will not cover building python classes in detail during boot-camp (since it is an advanced topic). 
<br /><br />
* However, we will introduce objects and classes here conceptually, because they are so fundamental. 
* So what are classes and objects? 

* **Classes are "blue prints" or "templates" for building customizable data-structures**
  *  Think of them as "customizable" boxes that can;
     *  (1) store **data** in what are known as "**attributes** of the class" 
         * These are comparable to how Dictionaries have keys and values
     *  (2) preform actions on themselves using **functions** which are known as "**methods** of the class".
  *  For example, if you wanted to build a custom data-structure to describe "animals" for a biology project.
     *  Then you could create a python class called "animal" to store information about the different animals in the study. 
     *  This class would be a "**template**" for define objects (see below) of the class "animal", for example
        * **Attributes** of class "animal"
           *  name
           *  species
        * **Methods** of class animal 
           * update_name(new_name) --> name=new_name  
           * i.e. change the animal's name with this method   
  <br />
     * **IN SUMMARY: CLASSES ARE "EMPTY TEMPLATES" FOR DEFINING OBJECTS** 
<br /><br />
*  **Objects are a particular instance of a class (i.e. a **populated template** of that class)**
   *  For example;
      * object_1: the first instance of class "animal"
         * object_1 attributes 
           * name="luna"
           * species="dog"
       * object_2: the second instance of class "animal"
         * object_2 attributes 
           * name="jack"
           * species="cat"
      * You can think of the "attributes" as metadata associated with the various objects
      * Also **both objects** would have access to the "update_name" method, which could be used at any time to change their name.
  <br /><br />
       * **IN SUMMARY: OBJECTS ARE "POPULATED TEMPLATES" (INSTANCES) OF A PARTICULAR CLASS** 
<br /><br />
* **In python attributes and methods of an object are accessed using "." at the end**
  * In the case of the previous example;
    * print(object_1.name) --> "luna"
    * print(object_1.species) --> "dog"
    * object_1.update_name("stinky")
    * print(object_1.name) --> "stinky"



In [1]:
#FOR MORE: https://docs.python.org/3/tutorial/classes.html

#REMEMBER 
#AND OBJECT IS A SPECIFIC INSTANCE OF A CLASS
#THE CLASS ITSELF IS A TEMPLATE FOR OBJECTS 
class Dog:

    # class variable shared by all instances
    kind = 'canine'        

    #INITIALIZE
    def __init__(self, attributions):
        self.name = attributions[0]      # instance variable unique to each instance
        self.weight = attributions[1]    
        self.possesions=[]               #initial as empty, fill later

    def increase_weight(self,dw=1):
    	self.weight+=dw

In [2]:
#INITIALIZE TWO OBJECTS OF CLASS DOG
L = Dog(['Luna' ,40])
S = Dog(['Spark',50])

In [3]:
#SEE INITIAL ATTRIBUTES
print("#-----------------------")
print(L.name, L.weight, L.kind)
print(S.name, S.weight, S.kind)

#-----------------------
Luna 40 canine
Spark 50 canine


In [4]:
#RUN THE increase_weight() METHOD
print("#-----------------------")
L.increase_weight()
print(L.name, L.weight, L.kind)
L.increase_weight(5)
print(L.name, L.weight, L.kind)

#-----------------------
Luna 41 canine
Luna 46 canine


In [5]:
#POPULATE POSSSESSION
print("#-----------------------")
print(S.name, S.weight, S.kind,S.possesions)
S.possesions=['collar','leash','bowl']
print(S.name, S.weight, S.kind,S.possesions)
S.possesions.append('dog food')
print(S.name, S.weight, S.kind,S.possesions)

#-----------------------
Spark 50 canine []
Spark 50 canine ['collar', 'leash', 'bowl']
Spark 50 canine ['collar', 'leash', 'bowl', 'dog food']


In [6]:


#SUBCLASS
    #NOTICE IT INHERITS ATTRIBUTIONS OF CLASS Dog
class SmallDog(Dog):
    size="small"
    # provides new attributions 
    # but does not break __init__()
    def update(self, H):
        self.height=H

In [7]:
B = SmallDog(['Bo' ,15])
B.update(1)
print(B.name, B.weight, B.kind, B.possesions,B.size,"H=",B.height)

Bo 15 canine [] small H= 1


**ASSIGNMENT**:
* Create a class called linear_algebra 
* use floats and python lists to store class objects as floats, vectors, and matrices
* provide an attribute for the objects of the class call .type = scalar, vector, matrix (don't need to do higher rank tensors)
* provide an attribute.shape which returns the shape of the vector 
* make a class method flatten() which acts on matrices and converts them into vector (lists)
* **Optional**:
  * make a class method "dot" that takes two objects, checks if they are vectors, and outputs the dot product (using a for-loop)
  * make a class method "prod" that takes two objects, checks if they are matrices, and outputs the matrix product (using a double for-loop)

In [45]:
class linear_algebra:

    #OBJECT CONSTRUCTOR 
    def __init__(self, input):
        input_type=str(type(input))
        self.data = input
        if(input_type=="<class 'float'>" or input_type=="<class 'int'>"):
            self.type  = "scalar"
            self.shape = (0,0)
        if(input_type=="<class 'list'>"):
            try:
                self.shape = (len(input),len(input[0]))
                self.type  = "matrix"
            except:
                self.type  = "vector"
                self.shape = (1,len(input))

    #FLATTEN A MATRIX INTO A VECTOR 
    def flatten(self):
        if(self.type  == "matrix"):
            tmp=[]
            for i in range(0,len(self.data)):
                for j in range(0,len(self.data[0])):
                    tmp.append(self.data[i][j])
            self.data=tmp
            self.type="vector"
            self.shape = (1,len(tmp))

    #DOT PROJECT 
    @staticmethod
    def dot(a, b):
        if(a.type == "vector" and b.type == "vector"):
            if(a.shape != b.shape):
                raise IndexError("linear_algebra.dot vectors must be same shape:",a.shape,b.shape)
            s=0
            for i in range(0,len(a.data)):
                s+=a.data[i]*b.data[i]
            # return linear_algebra(s)
            return s
        else:
            raise TypeError("linear_algebra.dot expects two vectors:",a.type,b.type)
        # return abs(person_a.age - person_b.age)

    #MATRIX MULTIPLICATION
    @staticmethod
    def matmul(a, b):
        if(a.type == "matrix" and b.type == "matrix"):
            if(a.shape[1] != b.shape[0]):
                raise IndexError("linear_algebra.matmul: inner dimensions must match:",a.shape,b.shape)
            #INITIALIZE
            c=[]
            for i in range(0,a.shape[0]):
                c.append([])
                for j in range(0,b.shape[1]):
                    c[i].append(0)
            
            #MATRIX MULTIPLY
            for i in range(0,a.shape[0]):
                s=0
                for j in range(0,b.shape[1]):
                    for k in range(0,a.shape[0]):
                        c[i][j] += a.data[i][k]*b.data[k][j]
            return linear_algebra(c)
        else:
            raise TypeError("linear_algebra.matmul expects two matrice:",a.type,b.type)


### Constructor function method:

The following code tests the constructor function

In [47]:
print("Scalar example:")
s = linear_algebra(1)
print(" ",s.type)
print(" ",s.shape)
print(" ",s.data)

print("Vector example:")
s = linear_algebra([1,2])
print(" ",s.type)
print(" ",s.shape)
print(" ",s.data)

print("Matrix example:")
s = linear_algebra([[1,2],[3,4]])
print(" ",s.type)
print(" ",s.shape)
print(" ",s.data)


Scalar example:
  scalar
  (0, 0)
  1
Vector example:
  vector
  (1, 2)
  [1, 2]
Matrix example:
  matrix
  (2, 2)
  [[1, 2], [3, 4]]


### Flatten method:

The following code tests the flatten method

In [41]:
s = linear_algebra([[1,2,3,4],[5,6,7,8]])
print(s.type)
print(s.shape)
print("original",s.data)
s.flatten()
print("flattened:",s.data)

matrix
(2, 4)
original [[1, 2, 3, 4], [5, 6, 7, 8]]
flattened: [1, 2, 3, 4, 5, 6, 7, 8]


### Dot product function:

The following code tests the dot product function

In [ ]:
s1 = linear_algebra([1,2])
s2 = linear_algebra([3,4])
s3=linear_algebra.dot(s1,s2)
print(s3)

### Matrix multiplication function:

The following code tests the matrix multiplication function

In [ ]:

print("Example-1:")
a = linear_algebra([[1,2],[3,4]])
b = linear_algebra([[1],[2]])
print("data=",a.data," shape=", a.shape)
print("data=",b.data," shape=", b.shape)
c=linear_algebra.matmul(a, b)
print("data=",c.data," shape=", c.shape)

print("Example-2:")
a = linear_algebra([[1,2],[3,4]])
b = linear_algebra([[1,2],[3,4]])
print("data=",a.data," shape=", a.shape)
print("data=",b.data," shape=", b.shape)
c=linear_algebra.matmul(a, b)
print("data=",c.data," shape=", c.shape)


### Additional code and hints

In [9]:

#EXAMPLE: CODE TO DETERMINE  SOMETHING IS; 
#   (1) LIST OF SCALARS (i.e. a vector) 
#   (2) A LIST OF LISTS (i.e a matrix)

x=[[1,2],[3,4]]
# google "python try except if you haven't used it before"
try: 
    print(len(x[0])) #this will throw an error 
    print("A: im a matrix") 
except:
    print("B: im a vector") 

x=[1,2,3,4]
# google "python try except if you haven't used it before"
try: 
    print(len(x[0])) #this will throw an error 
    print("A: im a matrix") 
except:
    print("B: im a vector") 

2
A: im a matrix
B: im a vector


In [36]:
# NOTE: YOUR CODE SHOULD BEHAVE SIMILAR TO NUMPY
# YOU CAN HANDEL "SHAPE" HOWEVER YOU WANT VECTOR --> (N,) or (N,1)
import numpy as np
print("VECTOR")
V = np.array([1,2,3]);
print(V)
print(V.shape)
print("MATRIX")
M = np.array([[1,2,3,4],[5,6,7,8]])
print(M)
print(M.shape)
print(M.flatten())



VECTOR
[1 2 3]
(3,)
MATRIX
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[1 2 3 4 5 6 7 8]
